image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn clean verify
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target\site\allure-maven-plugin