image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn clean verify
  artifacts:
      when: always
      reports:
        junit: 
          - target/site/index.html